language: go

go:
- 1.14

before_script:
  - go get -u github.com/jteeuwen/go-bindata/...
  - cp -f $GOPATH/bin/go-bindata /usr/local/bin/

script: make release

deploy:
  provider: releases
  api_key:
    secure: mvQvrgGEpX/teuj0OBiBaHtvbs5laQloYUzxHDyeSD2jLZMTUAwQdRYi2lanorXe/0P0M3Y9kw1tYRGzSWzc4IAotm+4Etez/v4rxte/7Fuzf8seahewUNFMPvFPhzywnroGdI2Q2mJNIc3r3PLDcCYRXxjUPMGOMRPDmNDxYOBLcM8dYBSjFbLvog24J8ZYWiXRHgFsIsvPjAiXHBRF2+AWvKP6P3b+7Qfr9pZ6JMADXzpWxGukCt3eP2Y3iGBZxwX5iA+hwkJNk4zOlwFE0avXyHAGxz+iUqlgqjPj5KR8nE4Rnzj6TzRYp8xjMFd5QtfZPKPX9eybq44H/1zoCfPoytGH/p4UWj6/xFr1JQmJ5czyslw6NbXEy18xExafGIu3m+U5PPAN1diZF53Q28QnZbt74QrY8NVAkXuy8gWiVHVQH4emcOW2U1JWR6WvUPLAHoDN719FPT09GeYPIFxHMjKGyGgaikiI9gFDPcy/surIlqZGoazfafVhfNaat7FkMWn3EBz0OLrIUQuCOSHz1vjHMAV1Ph6+XQykRUCk74DUIuybZKZ1AVRBfBW5SPW8OtCD0//33SRJGq207Z3eYV6rZwnKCJd5l4efroewmIZVIDTCDXyJFdfau+afgesA694i4z0SRyUxLi0EY7v3aYKtOm4ct5T2RlFqcQQ=
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    tags: true

