website-charset: UTF-8
zipfilename-charset: GBK

title:
    begin: <meta property="og:novel:book_name"
    end: />
    regexp: content="(.+)"
    name-index: 1

author:
    begin: <meta property="og:novel:author"
    end: />
    regexp: content="(.+)"
    name-index: 1

chapter:
    begin: <div id="list">
    end: </div>
    regexp: <a style="" href="([^>]+)">([^<]+)</a>
    link-index: 1
    name-index: 2

content:
    begin: <div id="content">
    end: <script>
